// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQzEcJiGkDUN5wIkS7CvDOxK_UCbE34Q',
    appId: '1:128034499784:web:3b56b4af8ff7f222a649fd',
    messagingSenderId: '128034499784',
    projectId: 'hostel-help-eed39',
    authDomain: 'hostel-help-eed39.firebaseapp.com',
    storageBucket: 'hostel-help-eed39.firebasestorage.app',
    measurementId: 'G-P6W36Q3XXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQAY0xkMCq1b6hHDMTGaC5HFE4gP8jT1A',
    appId: '1:128034499784:android:c75af07aea091f20a649fd',
    messagingSenderId: '128034499784',
    projectId: 'hostel-help-eed39',
    storageBucket: 'hostel-help-eed39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4uSVj9zHCPUIK4g4k2IMal4mTj3EUVo',
    appId: '1:128034499784:ios:c47921cf721cd293a649fd',
    messagingSenderId: '128034499784',
    projectId: 'hostel-help-eed39',
    storageBucket: 'hostel-help-eed39.firebasestorage.app',
    iosBundleId: 'com.example.hostelHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4uSVj9zHCPUIK4g4k2IMal4mTj3EUVo',
    appId: '1:128034499784:ios:c47921cf721cd293a649fd',
    messagingSenderId: '128034499784',
    projectId: 'hostel-help-eed39',
    storageBucket: 'hostel-help-eed39.firebasestorage.app',
    iosBundleId: 'com.example.hostelHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQzEcJiGkDUN5wIkS7CvDOxK_UCbE34Q',
    appId: '1:128034499784:web:91fbb399a7728deea649fd',
    messagingSenderId: '128034499784',
    projectId: 'hostel-help-eed39',
    authDomain: 'hostel-help-eed39.firebaseapp.com',
    storageBucket: 'hostel-help-eed39.firebasestorage.app',
    measurementId: 'G-GWV8WS06J7',
  );
}
